build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
args:
  aarch64:
    BUILD_GOARCH: arm64
  armv7:
    BUILD_GOARCH: arm
    BUILD_GOARM: "7"
  amd64:
    BUILD_GOARCH: amd64
